### ISSUE TITLE
KO - REFUSED

### ISSUE THREAD

**Issue by thwyster** [aarock1234/akinator-api#1]
Hi, I'm trying use example test with 'pt' region.

but after run test, I received: KO - REFUSED

the GET is correct? 
http://api-pt4.akinator.com/ws/new_session?callback=&partner=1&player=desktopPlayer

**Comment by Gtoyos** [comment]
@thwyster . Where did you find Akinator documentation? I can't find it anywhere

**Comment by thwyster** [comment]
@Gtoyos, 

I did not find the official documentation, but I entered the Akinator website and intercepted the POST / GET calls it does, so I got almost all the new Webservices, but the French ones did not get the correct one, because for the French language, they use 2 Ws, one for objects and one for Characters / People.

Here are the new WebServices:

Language.English  		=> 		"api-en4.akinator.com/ws"	
Language.Arabic			=> 		"api-ar3.akinator.com/ws"
Language.Chinese		=> 		"api-cn4.akinator.com/ws"
Language.German			=> 		"178.33.63.63:8005/ws"
Language.Spanish		=> 		"api-es3.akinator.com/ws"
Language.Frence			=> 		"api-fr3.akinator.com/ws"
Language.Hebrew			=> 		"178.33.63.63:8006/ws"
Language.Italian		=> 		"api-it2.akinator.com/ws"
Language.Japanese		=> 		"178.33.63.63:8012/ws"
Language.Korean			=> 		"api-kr4.akinator.com/ws"
Language.Nederlands		=> 		"api-nl2.akinator.com/ws"
Language.Polish			=> 		"api-pl3.akinator.com/ws"
Language.Portuguese		=> 		"api-pt4.akinator.com/ws"
Language.Russian		=> 		"api-ru4.akinator.com/ws"
Language.Turkish		=> 		"api-tr3.akinator.com/ws"

**Comment by jgoralcz** [comment]
I created my own npm package with promises, more features, and a back option with the updated uri's. It's called 'aki-api'. Open to fixes and pull requests because this package seems unsupported unfortunately.

**Comment by Gtoyos** [comment]
@thwyster 

The Ws seem to have changed. After intercepting POST/GET requests that akinator.com sends are like this now: 
https://srv6.akinator.com:9126/ws/answer?callback=jQuery331012933480820963106_1537742526308&session=151&signature=1931487911&step=0&answer=0&question_filter=&_=1537742526310

and the responses are now like this:
jQuery331012933480820963106_1537742526308({"completion":"OK","parameters":{"question":"Is your character a female?","answers":[{"answer":"Yes"},{"answer":"No"},{"answer":"Don't know"},{"answer":"Probably"},{"answer":"Probably not"}],"step":"1","progression":"6.44184","questionid":"226","infogain":"0.592799","status_minibase":"0","isnan":"0"}})

@jgoralcz Have you found a package that works atm?

**Comment by jgoralcz** [comment]
https://www.npmjs.com/package/aki-api

covers all the needed features, supports callbacks and async/await

@Gtoyos

**Comment by aarock1234** [comment]
I will be updating with even more features.
